rebase:shim

diff --git a/.github/workflows/macos-matrix.yml b/.github/workflows/macos-matrix.yml
--- a/.github/workflows/macos-matrix.yml
+++ b/.github/workflows/macos-matrix.yml
@@ -28,13 +28,26 @@ jobs:
     runs-on: ${{ matrix.os }}
     steps:
       - uses: styfle/cancel-workflow-action@0.11.0
+        if: ${{ ! env.ACT }}
         with:
           access_token: ${{ github.token }}
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
       - name: printenv
         run: |
-          brew install libtool autoconf automake cmake
           printenv
-      - name: cmake . && make secp256k1 all
+      - name: make
         run: |
-          cmake . && make secp256k1 all
+          type -P brew && brew install automake || echo "install automake"
+          make submodules
+          make all
+      - name: make install
+        run: |
+          sudo -S make install
+      - name: man nostril
+        run: |
+          type -P nostril && man nostril || echo "man nostril not working..."
+      - name: nostril
+        run: |
+          #pipe handles non-zero return from nostril default help
+          sudo make install > /dev/null 2>&1
+          type -P nostril && nostril --envelope -t nostril --content ""
